site_name: RCJ Soccer 2023
theme:
  name: material
  palette:
    primary: green

nav:
  - Home: index.md
  - Code Submission: "code-submission.md"
  - Submission check: "submission-check.md"
  - SoccerSim World Championship 2023: "world-competition.md"
  - SoccerSim World Championship 2023 results:
    - Technical Challenge Results: "results/tech-challenges.md"
    - Team Description Papers: "results/tdps.md"
    - Games: "results/games.md"
